Add documentation about organization
prospectio/prospectio-api-doc pull request #11
Opened 2020-11-03 12:23 UTC by aclarembeau

Note: 

We don't introduce yet a hard link between prospect & organization (and thus still allow using organization_name, until we update zapier, etc… )

2020-11-04 14:02 UTC, ThibaultW reviewed
Only 2 things to check about the record `id`, otherwise looks good.

2020-11-04 14:02 UTC, ThibaultW commented on source/includes_main/_organizations.md
> +id | *NULL* | A unique identifier for the organization
to remove for the `create` I think

2020-11-04 14:02 UTC, ThibaultW commented on source/includes_main/_organizations.md
> +id | A unique identifier for the organization
should we add that the id is required ? (like for the prospect update)

2020-11-06 14:11 UTC, Guaker13 requested changes
Nearly there; here are some comments.

2020-11-06 14:11 UTC, Guaker13 commented on source/includes/_relationships.md
> +GET https://api.prospect.io/public/v1/prospects/?include=organization
Is this URL correct? Shouldn't it be `https://api.prospect.io/public/v1/prospects?include=organization`, without trailing `/`?

2020-11-06 14:11 UTC, Guaker13 commented on source/includes/_relationships.md
> +In order to get access to associated information on an entity, you can use the parameter `?include=`, which will create
What if want many relationships to be included, i.e. prospect's creator and organization. Can I do `?include=creator,organization`? This needs to be precised.

2020-11-06 14:11 UTC, Guaker13 commented on source/includes_main/_organizations.md
> +</aside>
At this point this is not true since no message or reply are linked to orgs.

2020-11-06 14:23 UTC, merged